### ISSUE TITLE
Prebuilt solution for React Native

### ISSUE THREAD

**Issue by salmandayal** [videosdk-live/videosdk-rtc-prebuilt-examples#7]
Is there a prebuilt solution available for React Native so we can use prebuilt UI with React Native. It not showing in the examples list. Thanks

**Comment by ahmedbhesaniya97** [comment]
@salmandayal 
Currenltly, We don't have a React Native Prebuilt solution, but we do have a project sample that looks like a prebuilt web.

Example Link :
https://github.com/videosdk-live/videosdk-rtc-react-native-sdk-example

Download the Sample iOS app here: https://testflight.apple.com/join/LYj3QJPx

Download the Sample Android app here: https://appdistribution.firebase.dev/i/a4c63049415c4356
